# Master Database Configuration
master.datasource.url=jdbc:postgresql://localhost:5444/master-db
master.datasource.username=postgres
master.datasource.password=password
master.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080
logging.level.root=INFO