# Server Configuration
server.port=9090
logging.level.root=INFO
management.endpoints.web.exposure.include=health
management.metrics.binders.processor.enabled=false
management.metrics.binders.system.enabled=false
management.metrics.binders.process.enabled=false
management.metrics.enable.process=false
management.metrics.enable.system=false